name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-03"



[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjAzNTljMjgtOTEwZi00MTEzLWE5NjMtY2U1ODJiNjJjNzQyIiwidGVuYW50X2lkIjoiMTNlNmExM2RlM2E4OTBmMDRkOTcxMjBmZTAyMjEyNjVmMWMzZWRhNjhiMGE5ZjdjNDI1OTZjNDg1ZjEwMDg0YSIsImludGVybmFsX3NlY3JldCI6IjBhYzYzZjBmLWQxZGUtNDgxMi1iNTNiLWY3NGJjYzg3NWJlMiJ9.m3-ZC_0hucW-bNSbMafT8jt-5iNeBVrOvXjjYxLbUaI"
JWT_SECRET = "my-secret"


